### ISSUE TITLE
Error opening file

### ISSUE THREAD

**Issue by amalic** [chloridite/OpenBoardView#13]
I get an error message when trying your software. After looking for brd files i found one on github, which resulted in the error described.

https://github.com/sparkfun/Si4703_FM_Tuner_Evaluation_Board/blob/master/Hardware/SparkFun_Si4703_Eval.brd

**Comment by stray77** [comment]
This is an eagle cad file that just happens to share the same extension as the files we use.  They are not intended to be compatible.  I'm guessing you should close this issue.  Here is an example of a file that does work. 
[LB#820-2530 Macbook_13_A1278_K24.zip](https://github.com/chloridite/OpenBoardView/files/298189/LB.820-2530.Macbook_13_A1278_K24.zip)

**Comment by amalic** [comment]
thanks for the infos

**Comment by MattSturgeon** [comment]
If anyone is actually interested in eagle cad files, please open a new issue
